# Dépôts de MAJ
acl repos_http dstdomain .debian.org dl.fedoraproject.org repository.veeam.com .eset.com
acl repos_tls  ssl::server_name .debian.org dl.fedoraproject.org repository.veeam.com .eset.com

# no_internet : autorisé UNIQUEMENT vers ces dépôts
http_access allow from_transparent no_internet repos_http
http_access allow from_transparent no_internet step1 SSL_ports
http_access allow from_transparent no_internet repos_tls
http_access deny no_internet