#!/bin/sh
exec tail -n +3 $0
# /etc/grub.d/40_custom - protection du chargeur GRUB (parc Debian)
# Le hash est genere par grub-mkpasswd-pbkdf2 puis injecte ici,
# la configuration est regeneree par update-grub.
set superusers="root"
password_pbkdf2 root [REDACTED]
